apiVersion: v2
appVersion: v1.2.1
dependencies:
- condition: crds.enabled
  name: fabric-crds
  repository: ""
  version: 1.2.1
description: Kubernetes network fabric for multi-tenant clouds, a fork of fabric
home: https://github.com/cloudyfolks-labs/fabric
kubeVersion: '>= 1.29.0-0'
name: fabric
sources:
- https://github.com/cloudyfolks-labs/fabric
type: application
version: 1.2.1
