#!/usr/bin/env bash
set -euo pipefail

dir=${1:-dist/release}

test -f "$dir/release.yaml"
test -f "$dir/images.txt"
for group in 00-crds 10-kube-vip 20-fabric 25-multus 30-nmstate 40-rook 41-rook-csi 50-kubevirt 60-cert-manager 65-traefik 70-monitoring 80-kured 90-bedrock; do
  test -d "$dir/manifests/$group"
done
grep -q 'kind: CustomResourceDefinition' "$dir/manifests/00-crds/cert-manager-crds.yaml"
grep -q 'kind: DaemonSet' "$dir/manifests/10-kube-vip/kube-vip.yaml"
grep -q 'name: fabric' "$dir/manifests/20-fabric/fabric.yaml"
grep -q 'BEDROCK_MASTER_IPS' "$dir/manifests/20-fabric/fabric.yaml"
grep -q 'kind: CustomResourceDefinition' "$dir/manifests/00-crds/fabric-crds.yaml"
grep -q 'kind: DaemonSet' "$dir/manifests/25-multus/multus.yaml"
grep -q 'multus-cni:v4.3.1-thick' "$dir/manifests/25-multus/multus.yaml"
grep -q 'name: network-attachment-definitions.k8s.cni.cncf.io' "$dir/manifests/00-crds/multus-crds.yaml"
! grep -q 'kind: CustomResourceDefinition' "$dir/manifests/25-multus/multus.yaml"
grep -q 'name: nmstate-operator' "$dir/manifests/30-nmstate/nmstate.yaml"
grep -q 'kind: NMState' "$dir/manifests/30-nmstate/nmstate.yaml"
grep -q 'name: nmstates.nmstate.io' "$dir/manifests/00-crds/nmstate-crds.yaml"
grep -q 'kubernetes-nmstate-handler:v0.87.0' "$dir/images.txt"
grep -q 'name: rook-ceph-operator' "$dir/manifests/40-rook/rook.yaml"
grep -q 'name: snapshot-controller' "$dir/manifests/40-rook/rook.yaml"
grep -q 'snapshot-controller:v8.5.0' "$dir/manifests/40-rook/rook.yaml"
grep -q 'name: cephclusters.ceph.rook.io' "$dir/manifests/00-crds/rook-crds.yaml"
grep -q 'name: volumesnapshotclasses.snapshot.storage.k8s.io' "$dir/manifests/00-crds/rook-crds.yaml"
grep -q 'name: drivers.csi.ceph.io' "$dir/manifests/00-crds/rook-crds.yaml"
grep -q 'kind: Driver' "$dir/manifests/41-rook-csi/rook-csi.yaml"
grep -q 'name: virt-operator' "$dir/manifests/50-kubevirt/kubevirt.yaml"
grep -q 'name: cdi-operator' "$dir/manifests/50-kubevirt/kubevirt.yaml"
grep -q 'name: kubevirts.kubevirt.io' "$dir/manifests/00-crds/kubevirt-crds.yaml"
grep -q 'name: cdis.cdi.kubevirt.io' "$dir/manifests/00-crds/kubevirt-crds.yaml"
grep -q 'quay.io/kubevirt/virt-launcher:v1.9.0' "$dir/images.txt"
grep -q 'quay.io/ceph/ceph:v20.2.4' "$dir/images.txt"
grep -q 'quay.io/cephcsi/cephcsi:v3.17.1' "$dir/images.txt"
grep -q 'image: quay.io/ceph/ceph:v20.2.4' "$dir/release.yaml"
grep -q 'name: cert-manager' "$dir/manifests/60-cert-manager/cert-manager.yaml"
grep -q 'kind: Service' "$dir/manifests/65-traefik/traefik.yaml"
grep -q 'kube-vip.io/loadbalancerIPs: \${BEDROCK_VIP}' "$dir/manifests/65-traefik/traefik.yaml"
grep -q 'kind: TLSStore' "$dir/manifests/65-traefik/traefik.yaml"
grep -q 'name: ingressroutes.traefik.io' "$dir/manifests/00-crds/traefik-crds.yaml"
grep -q 'endpointslices' "$dir/manifests/10-kube-vip/kube-vip.yaml"
grep -q 'metrics-server' "$dir/manifests/70-monitoring/monitoring.yaml"
grep -q 'kind: DaemonSet' "$dir/manifests/80-kured/kured.yaml"
grep -q 'name: bedrock-operator' "$dir/manifests/90-bedrock/bedrock.yaml"
grep -q 'kind: ValidatingAdmissionPolicy' "$dir/manifests/90-bedrock/bedrock.yaml"
! grep -rq 'ghcr.io/cloudyfolks-labs/bedrock:dev' "$dir/manifests" || test "$(grep '^version:' "$dir/release.yaml")" = "version: dev"
echo "check-release passed"
