apiVersion: v1
kind: Namespace
metadata:
  name: bedrock-system
  labels:
    bedrock.cloudyfolks.io/component: bedrock
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bedrock-operator
  namespace: bedrock-system
  labels:
    bedrock.cloudyfolks.io/component: bedrock
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bedrock-operator
  labels:
    bedrock.cloudyfolks.io/component: bedrock
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: bedrock-operator
    namespace: bedrock-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bedrock-operator
  namespace: bedrock-system
  labels:
    bedrock.cloudyfolks.io/component: bedrock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bedrock-operator
  template:
    metadata:
      labels:
        app: bedrock-operator
    spec:
      serviceAccountName: bedrock-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      containers:
        - name: operator
          image: ghcr.io/cloudyfolks-labs/bedrock:dev
          args: ["operator"]
          env:
            - name: BEDROCK_RELEASE_DIR
              value: /release
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
